################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_fast_opt_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_fast_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_fast_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_opt_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_opt_q7.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_partial_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_partial_fast_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_partial_fast_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_partial_opt_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_partial_opt_q7.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_partial_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_partial_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_partial_q7.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_conv_q7.c \
../Middlewares/DSP/FilteringFunctions/arm_correlate_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_correlate_fast_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_correlate_fast_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_correlate_opt_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_correlate_opt_q7.c \
../Middlewares/DSP/FilteringFunctions/arm_correlate_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_correlate_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_correlate_q7.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_decimate_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_decimate_init_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_decimate_init_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_decimate_init_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_decimate_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_decimate_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_fast_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_fast_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_init_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_init_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_init_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_init_q7.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_lattice_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_lattice_init_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_lattice_init_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_lattice_init_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_lattice_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_lattice_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_q7.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_sparse_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_q7.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_sparse_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_sparse_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_fir_sparse_q7.c \
../Middlewares/DSP/FilteringFunctions/arm_iir_lattice_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_iir_lattice_init_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_iir_lattice_init_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_iir_lattice_init_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_iir_lattice_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_iir_lattice_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_init_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_init_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_init_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_norm_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_norm_init_f32.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_norm_init_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_norm_init_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_norm_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_norm_q31.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_q15.c \
../Middlewares/DSP/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_fast_opt_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_fast_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_fast_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_opt_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_opt_q7.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_fast_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_fast_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_opt_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_opt_q7.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_q7.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_conv_q7.o \
./Middlewares/DSP/FilteringFunctions/arm_correlate_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_correlate_fast_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_correlate_fast_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_correlate_opt_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_correlate_opt_q7.o \
./Middlewares/DSP/FilteringFunctions/arm_correlate_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_correlate_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_correlate_q7.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_init_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_init_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_init_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_fast_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_fast_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_init_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_init_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_init_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_init_q7.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_init_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_init_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_init_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_q7.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_q7.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_q7.o \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_init_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_init_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_init_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_init_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_init_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_init_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_init_f32.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_init_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_init_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_q31.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_q15.o \
./Middlewares/DSP/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_fast_opt_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_fast_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_fast_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_opt_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_opt_q7.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_fast_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_fast_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_opt_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_opt_q7.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_partial_q7.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_conv_q7.d \
./Middlewares/DSP/FilteringFunctions/arm_correlate_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_correlate_fast_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_correlate_fast_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_correlate_opt_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_correlate_opt_q7.d \
./Middlewares/DSP/FilteringFunctions/arm_correlate_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_correlate_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_correlate_q7.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_init_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_init_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_init_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_decimate_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_fast_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_fast_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_init_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_init_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_init_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_init_q7.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_interpolate_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_init_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_init_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_init_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_lattice_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_q7.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_init_q7.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_fir_sparse_q7.d \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_init_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_init_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_init_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_iir_lattice_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_init_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_init_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_init_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_init_f32.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_init_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_init_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_norm_q31.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_q15.d \
./Middlewares/DSP/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/DSP/FilteringFunctions/%.o: ../Middlewares/DSP/FilteringFunctions/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DUSE_HAL_DRIVER -DSTM32F746xx -I"D:/workspace/ethernet_lights/Inc" -I"D:/workspace/ethernet_lights/Middlewares/Third_Party/LwIP/src/include" -I"D:/workspace/ethernet_lights/Middlewares/Third_Party/LwIP/system" -I"D:/workspace/ethernet_lights/Drivers/STM32F7xx_HAL_Driver/Inc" -I"D:/workspace/ethernet_lights/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy" -I"D:/workspace/ethernet_lights/Middlewares/Third_Party/LwIP/src/include/netif/ppp" -I"D:/workspace/ethernet_lights/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"D:/workspace/ethernet_lights/Middlewares/Third_Party/LwIP/src/include/lwip" -I"D:/workspace/ethernet_lights/Middlewares/Third_Party/LwIP/src/include/lwip/apps" -I"D:/workspace/ethernet_lights/Middlewares/Third_Party/LwIP/src/include/lwip/priv" -I"D:/workspace/ethernet_lights/Middlewares/Third_Party/LwIP/src/include/lwip/prot" -I"D:/workspace/ethernet_lights/Middlewares/Third_Party/LwIP/src/include/netif" -I"D:/workspace/ethernet_lights/Middlewares/Third_Party/LwIP/src/include/posix" -I"D:/workspace/ethernet_lights/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"D:/workspace/ethernet_lights/Middlewares/Third_Party/LwIP/system/arch" -I"D:/workspace/ethernet_lights/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


